version: '3'
services:
  reverse-1:
    #image: hf18-reverse-1
    build: /hf18/challenges/reverse-1
    ports:
      - "0.0.0.0:5013:22"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
